function createaxes(Parent1, X1, Y1)
%CREATEAXES(Parent1, X1, Y1)
%  PARENT1:  axes parent
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 01-Oct-2019 11:46:52

% Create axes
axes1 = axes('Parent',Parent1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'YTick',[55000 60000 65000 70000 75000 80000 ]);
